# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f3c58a2c7c216b4d8b2caff6903323296ad5477074336289bc87376d6427e1eec03d68f4c6eacb6f0d58e74fdb96b618e103020bda1f28337e8e4f39ae633f9

test:
  secret_key_base: 9733d59d43bbf4c052301049d56e271591784291d8e0b89445ea2762b21a8c82a18d8ae7820e3e5786637dc1bc500a0c9969cfab42fb6cf004848ecbab3cd2a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
